CATEGORIES = [
    "Housing & Rent",
    "Food & Dining",
    "Groceries & Essentials",
    "Transportation",
    "Shopping & Lifestyle",
    "Entertainment & Subscriptions",
    "Utilities & Bills",
    "Healthcare",
    "Education",
    "Friends and Relatives",
    "Income",
    "Financial & Investments",
    "Others / Uncategorized",
]

MERCHANT_CATEGORY_MAP = {
    "swiggy": "Food & Dining",
    "zomato": "Food & Dining",
    "dominos": "Food & Dining",
    "pizza": "Food & Dining",
    "restaurant": "Food & Dining",
    "cafe": "Food & Dining",
    "reliance": "Groceries & Essentials",
    "dmart": "Groceries & Essentials",
    "bigbasket": "Groceries & Essentials",
    "grocery": "Groceries & Essentials",
    "uber": "Transportation",
    "ola": "Transportation",
    "irctc": "Transportation",
    "railways": "Transportation",
    "metro": "Transportation",
    "bmtc": "Transportation",
    "amazon": "Shopping & Lifestyle",
    "flipkart": "Shopping & Lifestyle",
    "myntra": "Shopping & Lifestyle",
    "ajio": "Shopping & Lifestyle",
    "decathlon": "Shopping & Lifestyle",
    "netflix": "Entertainment & Subscriptions",
    "spotify": "Entertainment & Subscriptions",
    "youtube": "Entertainment & Subscriptions",
    "prime": "Entertainment & Subscriptions",
    "bookmyshow": "Entertainment & Subscriptions",
    "pvr": "Entertainment & Subscriptions",
    "electricity": "Utilities & Bills",
    "water": "Utilities & Bills",
    "gas": "Utilities & Bills",
    "broadband": "Utilities & Bills",
    "recharge": "Utilities & Bills",
    "airtel": "Utilities & Bills",
    "jio": "Utilities & Bills",
    "apollo": "Healthcare",
    "pharma": "Healthcare",
    "hospital": "Healthcare",
    "clinic": "Healthcare",
    "medical": "Healthcare",
    "udemy": "Education",
    "coursera": "Education",
    "school": "Education",
    "college": "Education",
    "salary": "Income",
    "interest": "Income",
    "refund": "Income",
    "dividend": "Income",
    "groww": "Financial & Investments",
    "zerodha": "Financial & Investments",
    "mutual": "Financial & Investments",
    "credit card": "Financial & Investments",
    "loan": "Financial & Investments",
    "emi": "Financial & Investments",
    "rent": "Housing & Rent",
    "maintenance": "Housing & Rent",
    "property tax": "Housing & Rent",
    "home loan": "Housing & Rent",
}
