CATEGORIES = [
    "Housing & Rent",
    "Food & Dining",
    "Groceries & Essentials",
    "Transportation",
    "Shopping & Lifestyle",
    "Entertainment & Subscriptions",
    "Utilities & Bills",
    "Healthcare",
    "Education",
    "Insurance & Protection",
    "Travel",
    "Friends and Relatives",
    "Income",
    "Financial & Investments",
    "Others / Uncategorized",
]

MERCHANT_CATEGORY_MAP = {
    # Food & Dining
    "swiggy": "Food & Dining",
    "zomato": "Food & Dining",
    "dominos": "Food & Dining",
    "pizza": "Food & Dining",
    "restaurant": "Food & Dining",
    "cafe": "Food & Dining",
    "mcdonalds": "Food & Dining",
    "kfc": "Food & Dining",
    "burger king": "Food & Dining",
    "starbucks": "Food & Dining",
    "dunkin": "Food & Dining",
    "subway": "Food & Dining",
    "rotti": "Food & Dining",
    "biryani": "Food & Dining",
    "eatsure": "Food & Dining",
    "box8": "Food & Dining",
    # Groceries & Essentials
    "reliance": "Groceries & Essentials",
    "dmart": "Groceries & Essentials",
    "bigbasket": "Groceries & Essentials",
    "grocery": "Groceries & Essentials",
    "blinkit": "Groceries & Essentials",
    "zepto": "Groceries & Essentials",
    "instamart": "Groceries & Essentials",
    "jiomart": "Groceries & Essentials",
    "more supermarket": "Groceries & Essentials",
    "spar": "Groceries & Essentials",
    "nature basket": "Groceries & Essentials",
    # Transportation
    "uber": "Transportation",
    "ola": "Transportation",
    "irctc": "Transportation",
    "railways": "Transportation",
    "metro": "Transportation",
    "bmtc": "Transportation",
    "rapido": "Transportation",
    "ksrtc": "Transportation",
    "redbus": "Transportation",
    "petrol": "Transportation",
    "fuel": "Transportation",
    "diesel": "Transportation",
    "hp pump": "Transportation",
    "iocl": "Transportation",
    "bharat petroleum": "Transportation",
    "fastag": "Transportation",
    # Shopping & Lifestyle
    "amazon": "Shopping & Lifestyle",
    "flipkart": "Shopping & Lifestyle",
    "myntra": "Shopping & Lifestyle",
    "ajio": "Shopping & Lifestyle",
    "decathlon": "Shopping & Lifestyle",
    "nykaa": "Shopping & Lifestyle",
    "meesho": "Shopping & Lifestyle",
    "shoppers stop": "Shopping & Lifestyle",
    "lifestyle": "Shopping & Lifestyle",
    "croma": "Shopping & Lifestyle",
    "tata cliq": "Shopping & Lifestyle",
    # Entertainment & Subscriptions
    "netflix": "Entertainment & Subscriptions",
    "spotify": "Entertainment & Subscriptions",
    "youtube": "Entertainment & Subscriptions",
    "prime": "Entertainment & Subscriptions",
    "bookmyshow": "Entertainment & Subscriptions",
    "pvr": "Entertainment & Subscriptions",
    "hotstar": "Entertainment & Subscriptions",
    "disney": "Entertainment & Subscriptions",
    "jiocinema": "Entertainment & Subscriptions",
    "apple music": "Entertainment & Subscriptions",
    "google play": "Entertainment & Subscriptions",
    "sony liv": "Entertainment & Subscriptions",
    # Utilities & Bills
    "electricity": "Utilities & Bills",
    "water": "Utilities & Bills",
    "gas": "Utilities & Bills",
    "broadband": "Utilities & Bills",
    "recharge": "Utilities & Bills",
    "airtel": "Utilities & Bills",
    "jio": "Utilities & Bills",
    "bsnl": "Utilities & Bills",
    "vi ": "Utilities & Bills",
    "act fibernet": "Utilities & Bills",
    "bescom": "Utilities & Bills",
    "cesc": "Utilities & Bills",
    "tata power": "Utilities & Bills",
    # Healthcare
    "apollo": "Healthcare",
    "pharma": "Healthcare",
    "hospital": "Healthcare",
    "clinic": "Healthcare",
    "medical": "Healthcare",
    "medplus": "Healthcare",
    "netmeds": "Healthcare",
    "1mg": "Healthcare",
    "practo": "Healthcare",
    "manipal": "Healthcare",
    "fortis": "Healthcare",
    # Education
    "udemy": "Education",
    "coursera": "Education",
    "school": "Education",
    "college": "Education",
    "unacademy": "Education",
    "byju": "Education",
    "linkedin learning": "Education",
    "skillshare": "Education",
    # Insurance & Protection
    "lic": "Insurance & Protection",
    "insurance": "Insurance & Protection",
    "icici prudential": "Insurance & Protection",
    "hdfc life": "Insurance & Protection",
    "max life": "Insurance & Protection",
    "star health": "Insurance & Protection",
    "bajaj allianz": "Insurance & Protection",
    "policy": "Insurance & Protection",
    "premium": "Insurance & Protection",
    # Travel
    "makemytrip": "Travel",
    "goibibo": "Travel",
    "oyo": "Travel",
    "cleartrip": "Travel",
    "yatra": "Travel",
    "airbnb": "Travel",
    "airline": "Travel",
    "indigo": "Travel",
    "air india": "Travel",
    "spicejet": "Travel",
    "vistara": "Travel",
    "booking.com": "Travel",
    "hotel": "Travel",
    # Income
    "salary": "Income",
    "interest": "Income",
    "refund": "Income",
    "dividend": "Income",
    "cashback": "Income",
    # Financial & Investments
    "groww": "Financial & Investments",
    "zerodha": "Financial & Investments",
    "mutual": "Financial & Investments",
    "credit card": "Financial & Investments",
    "loan": "Financial & Investments",
    "emi": "Financial & Investments",
    "kuvera": "Financial & Investments",
    "coin": "Financial & Investments",
    "angel one": "Financial & Investments",
    "upstox": "Financial & Investments",
    # Housing & Rent
    "rent": "Housing & Rent",
    "maintenance": "Housing & Rent",
    "property tax": "Housing & Rent",
    "home loan": "Housing & Rent",
    "society": "Housing & Rent",
    "apartment": "Housing & Rent",
}
